### ISSUE TITLE
chore: update snapshot tests syntax

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1399]
use `test` instead of `assert` in the md files.

**Current**
<pre>
```yml @assert
- method: POST
  url: http://localhost:8080/graphql
  body:
    query: query { username }
```
</pre>

**Proposed**
<pre>
```yml @test
- method: POST
  url: http://localhost:8080/graphql
  body:
    query: query { username }
```
</pre>
