### ISSUE TITLE
refactor: merge benchmarks

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#1829]
Currently, all the benchmarks are independently specified in the `cargo.toml` file. We would like to merge them together with more meaningful names. 

**Current**
```toml
[[bench]]
name = "json_like_bench"
harness = false

[[bench]]
name = "request_template_bench"
harness = false

[[bench]]
name = "data_loader_bench"
harness = false

[[bench]]
name = "impl_path_string_for_evaluation_context"
harness = false

[[bench]]
name = "protobuf_convert_output"
harness = false
```

**Proposed**
```toml
[[bench]]
name = "tailcall_benches"
harness = false
```
