### ISSUE TITLE
Config Generator Incorrectly Parses UUID as Argument Due to Leading Digits

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#2563]
### Issue Description

The config generator is incorrectly parsing UUIDs as arguments when the first three digits of the UUID are integers. This leads to incorrect GraphQL config generation. This issue was partially addressed in [#2347](https://github.com/tailcallhq/tailcall/issues/2347).

**Example:**

Given the following configuration:

```yaml
  - curl:
      src: "https://example.com/api/v2/order/597ad6e9-ee1a-406a-842f-c9c62564d24e/status/"
      fieldName: "orderStatus"
      headers: *headers
```

**Current Behavior:**

The generated GraphQL query is incorrect:

```graphql
orderStatus(p1: Int!): OrderStatus @http(path: "/api/v2/order/{{.args.p1}}ad6e9-ee1a-406a-842f-c9c62564d24e/status/")
```
**Expected Behaviour**
```graphql
orderStatus(id: String!): OrderStatus @http(path: "/api/v2/order/{{.args.id}}/status/")
```

**Ideal Expected Behavior after #2347 :**
```graphql
orderStatus: OrderStatus @http(path: "/api/v2/order/597ad6e9-ee1a-406a-842f-c9c62564d24e/status/")
```

The UUID should be treated as a single string, not parsed into arguments:

```graphql
orderStatus(id: String!): OrderStatus @http(path: "/api/v2/order/{{.args.id}}/status/")
```
