### ISSUE TITLE
Singularization Not Working Correctly for Certain Field Names

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#2564]
### Issue Description

The singularization process in the config generator is not working correctly in certain cases. For example, the field name `orderStatus` is being incorrectly converted to `OrderStatu` instead of `OrderStatus`.

**Example:**

Given the following configuration:

```yaml
  - curl:
      src: "https://example.com/api/v2/order/597ad6e9-ee1a-406a-842f-c9c62564d24e/status/"
      fieldName: "orderStatus"
      headers: *headers
```

**Current Behavior:**

The generated GraphQL query incorrectly singularizes the type name:

```graphql
orderStatus(id: String!): OrderStatu @http(path: "/api/v2/order/{{.args.id}}/status/")
```

**Expected Behavior:**

The singularization should correctly handle the field name:

```graphql
orderStatus(id: String!): OrderStatus @http(path: "/api/v2/order/{{.args.id}}/status/")
```
