### ISSUE TITLE
Support mustache templates in all `string` fields `generate::config`

### ISSUE THREAD

**Issue by tusharmath** [tailcallhq/tailcall#2646]
Config should support mustache templates everywhere there is a "String" type. 

**Technical Requirements**
- Templates should be able to resolve env variables.

**Before**

```yml
inputs:
- curl:
    src: https://example.com
    headers:
      user-agent: tailcall-v1
    fieldName: test
output: {}
schema: {}
```

**After**
```yml
inputs:
- curl:
    src: https://example.com
    headers:
      user-agent: "{{.env.USER}}"
    fieldName: test
output: {}
schema: {}
preset:
  inferTypeNames: true
```
