### ISSUE TITLE
Bug If I need to inlining UserData fails in jit

### ISSUE THREAD

**Issue by amitksingh1490** [tailcallhq/tailcall#2809]
Make this snapshot test pass. this test passes when jit is disabled but fails with `not implemented` if JIT is enabled

```markdown
	# Add field

	```graphql @config
	schema @server(enableJIT: false) {
	  query: Query
	}
	
	type User @addField(name: "lat", path: ["address", "geo", "lat"]) {
	  address: Address
	}
	
	type Address {
	  geo: Geo
	}
	
	type Geo {
	  lat: String
	}
	
	type UserData {
	  data: User
	}
	
	type Query @addField(name: "user", path: ["user","data"]) {
	  user(id: Int!): UserData @http(path: "/users/1", baseURL: "http://jsonplaceholder.typicode.com") @omit
	}
	```
	
	```yml @mock
	- request:
	    method: GET
	    url: http://jsonplaceholder.typicode.com/users/1
	  response:
	    status: 200
	    body:
	      data:
	        address:
	          geo:
	            lat: "-37.3159"
	        id: 1
	        name: foo
	```
	
	```yml @test
	- method: POST
	  url: http://localhost:8080/graphql
	  body:
	    query: query { user { lat } }
	```
```
